export const STRINGS = {
  CONFIG_PATH: ".github/ubiquibot-config.yml",
  UBIQUITY: "ubiquity",
  BILLING: "billing",
  USER_2: "user2",
  TEST_REPO: "test-repo",
  SHA_1: "1234",
  UBQ_EMAIL: "ubiquity@ubq",
  CONFIG_CHANGED_IN_COMMIT: "Files changed in the commits: .github/ubiquibot-config.yml",
  PUSHER_NOT_AUTHED: "Pusher is not authorized",
  SENDER_NOT_AUTHED: "Sender is not authorized",
  ZERO_SHA: "0000000000000000000000000000000000000000",
  BASE_RATE_FILES: [".github/ubiquibot-config.yml", ".github/.ubiquibot-config.yml"],
  USER_UBIQUITY_IS_AUTHORIZED: "User ubiquity is authorized to make changes",
  USER_BILLING_IS_AUTHORIZED: "User billing is authorized to make changes",
  ROLLING_BACK_CHANGES: "Rolling back changes",
  COMMIT_URL: "https://github.com/ubiquity/test-repo/commit/1",
  REPO_UPDATED_SUCCESSFULLY: "Repository updated successfully",
  LOGS_ANONYMOUS: "_Logs.<anonymous>",
};
